
name: continuous-development

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  MONGODB_URI: ${{secrets.MONGODB_URI}}
  SMTP_EMAIL: ${{secrets.SMTP_EMAIL}}
  SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}
  IMAGEKIT_PRIVATE_KEY: ${{secrets.IMAGEKIT_PRIVATE_KEY}}
  AZURE_WEBAPP_NAME: 3900cowhorse   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '/capstone'    # set this to the path to your web app project, defaults to the repository root
on:
  push:
    branches: [ "master" ]

jobs:
  azure-build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test
    - name: 'Deploy to Azure WebApp Service'
      uses: azure/webapps-deploy@v3
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}