
name: continuous-development

env:
  MONGODB_URI: ${{secrets.MONGODB_URI}}
  SMTP_EMAIL: ${{secrets.SMTP_EMAIL}}
  SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}
  IMAGEKIT_PRIVATE_KEY: ${{secrets.IMAGEKIT_PRIVATE_KEY}}
  
on:
  push:
    branches: [ "master" ]

jobs:
  azure-build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test
    - name: Build the Next.js app
      run: npm run build